version: '3'

networks:
    proxy:
        external: true
    internal:
        external: false

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - database_data:/var/lib/mysql
        networks:
            - internal
        labels:
            - traefik.enable=false
    adminer:
        image: adminer:4.3.1-standalone
        labels:
          - traefik.backend=adminer
          - traefik.frontend.rule=Host:db.unigrow.ttrks.de
          - traefik.docker.network=proxy
          - traefik.port=8080
        networks:
          - internal
          - proxy
        depends_on:
          - mariadb
    php-apache:
        image: eu.gcr.io/unigrow-169812/php-apache:latest
        container_name: php-apache
        labels:
              - traefik.backend=unigrow-php-apache
              - traefik.frontend.rule=Host:db.unigrow.ttrks.de
              - traefik.docker.network=proxy
              - traefik.port=80
        networks:
            - internal
            - proxy
        links:
            - mariadb:mysql
volumes:
    database_data:
